include ../../common.mk

ifneq ($(CFG_WSL),)
$(call install,00644,auto.wsl-disk)
$(call install,00644,auto.wsl-linux)
$(call install,00644,auto.wsl-net)
$(call install,00644,auto.wsl-net-share)
endif
